# Github repository for GoTyme Case Study Interview

## Dataset Overview

In [14]:
import pandas as pd
df = pd.read_csv('dataset.csv', sep='|')

print("Dataset shape:", df.shape)
df.info()
df.head()

Dataset shape: (35000, 21)
<class 'pandas.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Feature_ae_0   35000 non-null  int64
 1   Feature_dn_1   35000 non-null  int64
 2   Feature_cn_2   35000 non-null  int64
 3   Feature_ps_3   35000 non-null  int64
 4   Feature_ps_4   35000 non-null  int64
 5   Feature_ee_5   35000 non-null  float64
 6   Feature_cx_6   35000 non-null  float64
 7   Feature_cx_7   35000 non-null  float64
 8   Feature_em_8   35000 non-null  float64
 9   Feature_nd_9   35000 non-null  float64
 10  Feature_jd_10  35000 non-null  str
 11  Feature_md_11  35000 non-null  str
 12  Feature_ed_12  35000 non-null  str
 13  Feature_dd_13  35000 non-null  str
 14  Feature_hd_14  35000 non-null  str
 15  Feature_ld_15  35000 non-null  str
 16  Feature_cd_16  35000 non-null  str
 17  Feature_md_17  35000 non-null  str
 18  Feature_dd_18  35000 non-null  str
 19  Feature_pd_19  35000 non-null  str
 20  Response       35000 non-null  int64
dtypes: float64(5), int64(6), str(10)
memory usage: 9.3 MB

,Feature_ae_0,Feature_dn_1,Feature_cn_2,Feature_ps_3,Feature_ps_4,Feature_ee_5,Feature_cx_6,Feature_cx_7,Feature_em_8,Feature_nd_9,...,Feature_md_11,Feature_ed_12,Feature_dd_13,Feature_hd_14,Feature_ld_15,Feature_cd_16,Feature_md_17,Feature_dd_18,Feature_pd_19,Response
0,57,371,1,999,1,-1.8,92.893,-46.2,1.299,5099.1,...,Cat_1_m***d,Cat_3_h***l,Cat_0_n***o,Cat_0_n***o,Cat_2_y***s,Cat_0_c***r,Cat_6_m***y,Cat_1_m***n,Cat_0_f***e,0
1,55,285,2,999,0,1.1,93.994,-36.4,4.860,5191.0,...,Cat_1_m***d,Cat_7_u***n,Cat_1_u***n,Cat_2_y***s,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_2_t***u,Cat_1_n***t,0
2,33,52,1,999,1,-1.8,92.893,-46.2,1.313,5099.1,...,Cat_1_m***d,Cat_2_b***y,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_6_m***y,Cat_0_f***i,Cat_0_f***e,0
3,36,355,4,999,0,1.4,94.465,-41.8,4.967,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_4_j***n,Cat_0_f***i,Cat_1_n***t,0
4,27,189,2,999,0,1.4,93.918,-42.7,4.963,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_0_f***i,Cat_1_n***t,0

## Renaming Column Names based on Data Dictionary

In [15]:
# Rename columns using the provided data dictionary for readability while working with the dataset
column_mapping = {
    "Feature_ae_0": "customer_age",
    "Feature_dn_1": "last_call_duration_seconds",
    "Feature_cn_2": "call_attempts",
    "Feature_ps_3": "days_since_last_campaign",
    "Feature_ps_4": "prev_campaign_call_attempts",
    "Feature_ee_5": "employment_variation_rate_q",
    "Feature_cx_6": "consumer_price_index_m",
    "Feature_cx_7": "consumer_confidence_index_m",
    "Feature_em_8": "interbank_rate_3m_q",
    "Feature_nd_9": "num_employees_q",
    "Feature_jd_10": "employment_type",
    "Feature_md_11": "customer_civil_status",
    "Feature_ed_12": "education_level",
    "Feature_dd_13": "credit_facility_default",
    "Feature_hd_14": "has_home_loan",
    "Feature_ld_15": "has_personal_loan",
    "Feature_cd_16": "contact_medium",
    "Feature_md_17": "last_contact_month",
    "Feature_dd_18": "last_contact_weekday",
    "Feature_pd_19": "previous_campaign_outcome",
    "Response": "response"
}

df = df.rename(columns=column_mapping)

# Optional: preview renamed columns
print(df.columns.tolist())

df.head(10)

['customer_age', 'last_call_duration_seconds', 'call_attempts', 'days_since_last_campaign', 'prev_campaign_call_attempts', 'employment_variation_rate_q', 'consumer_price_index_m', 'consumer_confidence_index_m', 'interbank_rate_3m_q', 'num_employees_q', 'employment_type', 'customer_civil_status', 'education_level', 'credit_facility_default', 'has_home_loan', 'has_personal_loan', 'contact_medium', 'last_contact_month', 'last_contact_weekday', 'previous_campaign_outcome', 'response']

,customer_age,last_call_duration_seconds,call_attempts,days_since_last_campaign,prev_campaign_call_attempts,employment_variation_rate_q,consumer_price_index_m,consumer_confidence_index_m,interbank_rate_3m_q,num_employees_q,...,customer_civil_status,education_level,credit_facility_default,has_home_loan,has_personal_loan,contact_medium,last_contact_month,last_contact_weekday,previous_campaign_outcome,response
0,57,371,1,999,1,-1.8,92.893,-46.2,1.299,5099.1,...,Cat_1_m***d,Cat_3_h***l,Cat_0_n***o,Cat_0_n***o,Cat_2_y***s,Cat_0_c***r,Cat_6_m***y,Cat_1_m***n,Cat_0_f***e,0
1,55,285,2,999,0,1.1,93.994,-36.4,4.860,5191.0,...,Cat_1_m***d,Cat_7_u***n,Cat_1_u***n,Cat_2_y***s,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_2_t***u,Cat_1_n***t,0
2,33,52,1,999,1,-1.8,92.893,-46.2,1.313,5099.1,...,Cat_1_m***d,Cat_2_b***y,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_6_m***y,Cat_0_f***i,Cat_0_f***e,0
3,36,355,4,999,0,1.4,94.465,-41.8,4.967,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_4_j***n,Cat_0_f***i,Cat_1_n***t,0
4,27,189,2,999,0,1.4,93.918,-42.7,4.963,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_0_f***i,Cat_1_n***t,0
5,58,605,1,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_1_m***d,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_2_y***s,Cat_0_c***r,Cat_3_j***l,Cat_0_f***i,Cat_1_n***t,0
6,48,243,1,999,0,1.1,93.994,-36.4,4.856,5191.0,...,Cat_1_m***d,Cat_3_h***l,Cat_1_u***n,Cat_2_y***s,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_4_w***d,Cat_1_n***t,0
7,51,24,7,999,0,1.4,93.444,-36.1,4.962,5228.1,...,Cat_0_d***d,Cat_6_u***e,Cat_1_u***n,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_2_t***u,Cat_1_n***t,0
8,24,126,4,999,0,1.4,94.465,-41.8,4.962,5228.1,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_2_y***s,Cat_2_y***s,Cat_1_t***e,Cat_4_j***n,Cat_4_w***d,Cat_1_n***t,0
9,36,43,4,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_0_d***d,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_2_y***s,Cat_0_c***r,Cat_3_j***l,Cat_1_m***n,Cat_1_n***t,0

## Missing Values

In [16]:
print("Missing values:")
print(df.isna().sum())

Missing values:
customer_age                   0
last_call_duration_seconds     0
call_attempts                  0
days_since_last_campaign       0
prev_campaign_call_attempts    0
employment_variation_rate_q    0
consumer_price_index_m         0
consumer_confidence_index_m    0
interbank_rate_3m_q            0
num_employees_q                0
employment_type                0
customer_civil_status          0
education_level                0
credit_facility_default        0
has_home_loan                  0
has_personal_loan              0
contact_medium                 0
last_contact_month             0
last_contact_weekday           0
previous_campaign_outcome      0
response                       0
dtype: int64

## Duplicates

In [17]:
print("Duplicated values:")
print(df.duplicated().sum())

Duplicated values:
11

In [18]:
duplicates = df[df.duplicated(keep=False)]

print("Rows involved in duplicates:", len(duplicates))
display(duplicates.sort_values(by=df.columns.tolist()))

Rows involved in duplicates: 22

,customer_age,last_call_duration_seconds,call_attempts,days_since_last_campaign,prev_campaign_call_attempts,employment_variation_rate_q,consumer_price_index_m,consumer_confidence_index_m,interbank_rate_3m_q,num_employees_q,...,customer_civil_status,education_level,credit_facility_default,has_home_loan,has_personal_loan,contact_medium,last_contact_month,last_contact_weekday,previous_campaign_outcome,response
13767,24,114,1,999,0,-1.8,93.075,-47.1,1.423,5099.1,...,Cat_2_s***e,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_0_a***r,Cat_3_t***e,Cat_1_n***t,0
34582,24,114,1,999,0,-1.8,93.075,-47.1,1.423,5099.1,...,Cat_2_s***e,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_0_a***r,Cat_3_t***e,Cat_1_n***t,0
16751,27,331,2,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_1_m***n,Cat_1_n***t,0
22628,27,331,2,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_1_m***n,Cat_1_n***t,0
8359,32,128,1,999,0,1.4,93.918,-42.7,4.968,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
13226,32,128,1,999,0,1.4,93.918,-42.7,4.968,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
7458,35,348,4,999,0,-1.8,92.893,-46.2,1.313,5099.1,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_6_m***y,Cat_0_f***i,Cat_1_n***t,0
15237,35,348,4,999,0,-1.8,92.893,-46.2,1.313,5099.1,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_6_m***y,Cat_0_f***i,Cat_1_n***t,0
11483,36,88,1,999,0,1.4,93.918,-42.7,4.966,5228.1,...,Cat_1_m***d,Cat_7_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
30101,36,88,1,999,0,1.4,93.918,-42.7,4.966,5228.1,...,Cat_1_m***d,Cat_7_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
14539,39,124,1,999,0,1.1,93.994,-36.4,4.855,5191.0,...,Cat_1_m***d,Cat_1_b***y,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_2_t***u,Cat_1_n***t,0
30802,39,124,1,999,0,1.1,93.994,-36.4,4.855,5191.0,...,Cat_1_m***d,Cat_1_b***y,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_2_t***u,Cat_1_n***t,0
27624,41,127,1,999,0,1.4,93.444,-36.1,4.966,5228.1,...,Cat_1_m***d,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_3_t***e,Cat_1_n***t,0
31587,41,127,1,999,0,1.4,93.444,-36.1,4.966,5228.1,...,Cat_1_m***d,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_3_t***e,Cat_1_n***t,0
2634,45,252,1,999,0,-2.9,92.469,-33.6,1.072,5076.2,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,1
25182,45,252,1,999,0,-2.9,92.469,-33.6,1.072,5076.2,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,1
26479,47,43,3,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_0_d***d,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
33631,47,43,3,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_0_d***d,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
6927,55,33,1,999,0,1.4,93.444,-36.1,4.965,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_1_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_1_m***n,Cat_1_n***t,0
7217,55,33,1,999,0,1.4,93.444,-36.1,4.965,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_1_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_1_m***n,Cat_1_n***t,0
10501,71,120,1,999,0,-3.4,92.431,-26.9,0.742,5017.5,...,Cat_2_s***e,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_8_o***t,Cat_3_t***e,Cat_1_n***t,0
23883,71,120,1,999,0,-3.4,92.431,-26.9,0.742,5017.5,...,Cat_2_s***e,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_8_o***t,Cat_3_t***e,Cat_1_n***t,0

In [19]:
duplicates = df[df.duplicated(keep=False)]

print("Rows involved in duplicates:", len(duplicates))
display(duplicates.sort_values(by=df.columns.tolist()))

Rows involved in duplicates: 22

,customer_age,last_call_duration_seconds,call_attempts,days_since_last_campaign,prev_campaign_call_attempts,employment_variation_rate_q,consumer_price_index_m,consumer_confidence_index_m,interbank_rate_3m_q,num_employees_q,...,customer_civil_status,education_level,credit_facility_default,has_home_loan,has_personal_loan,contact_medium,last_contact_month,last_contact_weekday,previous_campaign_outcome,response
13767,24,114,1,999,0,-1.8,93.075,-47.1,1.423,5099.1,...,Cat_2_s***e,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_0_a***r,Cat_3_t***e,Cat_1_n***t,0
34582,24,114,1,999,0,-1.8,93.075,-47.1,1.423,5099.1,...,Cat_2_s***e,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_0_a***r,Cat_3_t***e,Cat_1_n***t,0
16751,27,331,2,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_1_m***n,Cat_1_n***t,0
22628,27,331,2,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_1_m***n,Cat_1_n***t,0
8359,32,128,1,999,0,1.4,93.918,-42.7,4.968,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
13226,32,128,1,999,0,1.4,93.918,-42.7,4.968,5228.1,...,Cat_2_s***e,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
7458,35,348,4,999,0,-1.8,92.893,-46.2,1.313,5099.1,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_6_m***y,Cat_0_f***i,Cat_1_n***t,0
15237,35,348,4,999,0,-1.8,92.893,-46.2,1.313,5099.1,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_6_m***y,Cat_0_f***i,Cat_1_n***t,0
11483,36,88,1,999,0,1.4,93.918,-42.7,4.966,5228.1,...,Cat_1_m***d,Cat_7_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
30101,36,88,1,999,0,1.4,93.918,-42.7,4.966,5228.1,...,Cat_1_m***d,Cat_7_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
14539,39,124,1,999,0,1.1,93.994,-36.4,4.855,5191.0,...,Cat_1_m***d,Cat_1_b***y,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_2_t***u,Cat_1_n***t,0
30802,39,124,1,999,0,1.1,93.994,-36.4,4.855,5191.0,...,Cat_1_m***d,Cat_1_b***y,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_6_m***y,Cat_2_t***u,Cat_1_n***t,0
27624,41,127,1,999,0,1.4,93.444,-36.1,4.966,5228.1,...,Cat_1_m***d,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_3_t***e,Cat_1_n***t,0
31587,41,127,1,999,0,1.4,93.444,-36.1,4.966,5228.1,...,Cat_1_m***d,Cat_5_p***e,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_3_t***e,Cat_1_n***t,0
2634,45,252,1,999,0,-2.9,92.469,-33.6,1.072,5076.2,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,1
25182,45,252,1,999,0,-2.9,92.469,-33.6,1.072,5076.2,...,Cat_1_m***d,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,1
26479,47,43,3,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_0_d***d,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
33631,47,43,3,999,0,1.4,93.918,-42.7,4.962,5228.1,...,Cat_0_d***d,Cat_3_h***l,Cat_0_n***o,Cat_2_y***s,Cat_0_n***o,Cat_0_c***r,Cat_3_j***l,Cat_2_t***u,Cat_1_n***t,0
6927,55,33,1,999,0,1.4,93.444,-36.1,4.965,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_1_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_1_m***n,Cat_1_n***t,0
7217,55,33,1,999,0,1.4,93.444,-36.1,4.965,5228.1,...,Cat_1_m***d,Cat_3_h***l,Cat_1_u***n,Cat_0_n***o,Cat_0_n***o,Cat_0_c***r,Cat_1_a***g,Cat_1_m***n,Cat_1_n***t,0
10501,71,120,1,999,0,-3.4,92.431,-26.9,0.742,5017.5,...,Cat_2_s***e,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_8_o***t,Cat_3_t***e,Cat_1_n***t,0
23883,71,120,1,999,0,-3.4,92.431,-26.9,0.742,5017.5,...,Cat_2_s***e,Cat_6_u***e,Cat_0_n***o,Cat_0_n***o,Cat_0_n***o,Cat_1_t***e,Cat_8_o***t,Cat_3_t***e,Cat_1_n***t,0

In [20]:
df = df.drop_duplicates().reset_index(drop=True)
print(df.shape)

(34989, 21)

## Target Distribution

In [21]:

df["response"].value_counts()
df["response"].value_counts(normalize=True)

response
0    0.887708
1    0.112292
Name: proportion, dtype: float64

## Unique Categorical Values

In [22]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n")
    print(df[col].value_counts())

employment_type
Cat_0_a***.     8864
Cat_1_b***r     7857
Cat_9_t***n     5733
Cat_7_s***s     3351
Cat_4_m***t     2489
Cat_5_r***d     1464
Cat_2_e***r     1256
Cat_6_s***d     1215
Cat_3_h***d      901
Cat_10_u***d     839
Cat_8_s***t      727
Cat_11_u***n     293
Name: count, dtype: int64


customer_civil_status
Cat_1_m***d    21206
Cat_2_s***e     9812
Cat_0_d***d     3902
Cat_3_u***n       69
Name: count, dtype: int64


education_level
Cat_6_u***e    10309
Cat_3_h***l     8039
Cat_2_b***y     5176
Cat_5_p***e     4477
Cat_0_b***y     3533
Cat_1_b***y     1962
Cat_7_u***n     1476
Cat_4_i***e       17
Name: count, dtype: int64


credit_facility_default
Cat_0_n***o    27664
Cat_1_u***n     7322
Cat_2_y***s        3
Name: count, dtype: int64


has_home_loan
Cat_2_y***s    18287
Cat_0_n***o    15863
Cat_1_u***n      839
Name: count, dtype: int64


has_personal_loan
Cat_0_n***o    28835
Cat_2_y***s     5315
Cat_1_u***n      839
Name: count, dtype: int64


contact_medium
Cat_0_c***r    22232
Cat_1_t***e    12757
Name: count, dtype: int64


last_contact_month
Cat_6_m***y    11737
Cat_3_j***l     6120
Cat_1_a***g     5191
Cat_4_j***n     4539
Cat_7_n***v     3482
Cat_0_a***r     2230
Cat_8_o***t      602
Cat_9_s***p      478
Cat_5_m***r      457
Cat_2_d***c      153
Name: count, dtype: int64


last_contact_weekday
Cat_2_t***u    7353
Cat_1_m***n    7243
Cat_4_w***d    6898
Cat_3_t***e    6883
Cat_0_f***i    6612
Name: count, dtype: int64


previous_campaign_outcome
Cat_1_n***t    30181
Cat_0_f***e     3646
Cat_2_s***s     1162
Name: count, dtype: int64

C:\Users\Vernon\AppData\Local\Temp\ipykernel_15636\3792820604.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

#### days_since_last_campaign

In [23]:
is_999 = df["days_since_last_campaign"] == 999

print("Rows with 999:", is_999.sum())
print("Percentage:", round(is_999.mean() * 100, 2), "%")

print("\nThe other rows (not 999):")
print(df.loc[~is_999, "days_since_last_campaign"].describe())

Rows with 999: 33700
Percentage: 96.32 %

The other rows (not 999):
count    1289.000000
mean        6.076028
std         3.896820
min         0.000000
25%         3.000000
50%         6.000000
75%         7.000000
max        27.000000
Name: days_since_last_campaign, dtype: float64

In [24]:
print("999 vs previous_campaign_outcome:")
display(pd.crosstab(is_999, df["previous_campaign_outcome"]))

print("\n999 vs 'zero previous attempts':")
display(pd.crosstab(is_999, df["prev_campaign_call_attempts"] == 0))

999 vs previous_campaign_outcome:

previous_campaign_outcome  Cat_0_f***e  Cat_1_n***t  Cat_2_s***s
days_since_last_campaign
False                              127            0         1162
True                              3519        30181            0

999 vs 'zero previous attempts':

prev_campaign_call_attempts  False  True
days_since_last_campaign
False                         1289      0
True                          3519  30181

In [25]:
import numpy as np

df["prev_campaign_status"] = np.select(
    [
        df["prev_campaign_call_attempts"] == 0,
        (df["prev_campaign_call_attempts"] > 0) & (df["days_since_last_campaign"] == 999),
    ],
    ["no_prev_campaign", "prev_campaign_gap_unknown"],
    default="prev_campaign_gap_known",
)

df["days_since_prev_campaign"] = df["days_since_last_campaign"].replace(999, np.nan)

print(df["prev_campaign_status"].value_counts())
print("\nMissing in days_since_prev_campaign:", df["days_since_prev_campaign"].isna().sum())

prev_campaign_status
no_prev_campaign             30181
prev_campaign_gap_unknown     3519
prev_campaign_gap_known       1289
Name: count, dtype: int64

Missing in days_since_prev_campaign: 33700

In [26]:
df = df.drop_duplicates().reset_index(drop=True)
print(df.shape)

(34989, 23)

In [27]:
print("Zero-second calls:", (df["last_call_duration_seconds"] == 0).sum())
print("Customers with > 20 call attempts:", (df["call_attempts"] > 20).sum())
print("Customers older than 80:", (df["customer_age"] > 80).sum())
print("Customers younger than 18:", (df["customer_age"] < 18).sum())

display(df[["customer_age", "last_call_duration_seconds", "call_attempts"]]
        .quantile([0.5, 0.9, 0.99, 0.999]))

Zero-second calls: 4
Customers with > 20 call attempts: 134
Customers older than 80: 96
Customers younger than 18: 4

       customer_age  last_call_duration_seconds  call_attempts
0.500          38.0                      179.00            2.0
0.900          55.0                      550.00            5.0
0.990          71.0                     1268.00           14.0
0.999          86.0                     2129.12           29.0

## Categorical

In [28]:
cat_cols = df.select_dtypes(include="str").columns

for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

employment_type
employment_type
Cat_0_a***.     8864
Cat_1_b***r     7857
Cat_9_t***n     5733
Cat_7_s***s     3351
Cat_4_m***t     2489
Cat_5_r***d     1464
Cat_2_e***r     1256
Cat_6_s***d     1215
Cat_3_h***d      901
Cat_10_u***d     839
Cat_8_s***t      727
Cat_11_u***n     293
Name: count, dtype: int64

customer_civil_status
customer_civil_status
Cat_1_m***d    21206
Cat_2_s***e     9812
Cat_0_d***d     3902
Cat_3_u***n       69
Name: count, dtype: int64

education_level
education_level
Cat_6_u***e    10309
Cat_3_h***l     8039
Cat_2_b***y     5176
Cat_5_p***e     4477
Cat_0_b***y     3533
Cat_1_b***y     1962
Cat_7_u***n     1476
Cat_4_i***e       17
Name: count, dtype: int64

credit_facility_default
credit_facility_default
Cat_0_n***o    27664
Cat_1_u***n     7322
Cat_2_y***s        3
Name: count, dtype: int64

has_home_loan
has_home_loan
Cat_2_y***s    18287
Cat_0_n***o    15863
Cat_1_u***n      839
Name: count, dtype: int64

has_personal_loan
has_personal_loan
Cat_0_n***o    28835
Cat_2_y***s     5315
Cat_1_u***n      839
Name: count, dtype: int64

contact_medium
contact_medium
Cat_0_c***r    22232
Cat_1_t***e    12757
Name: count, dtype: int64

last_contact_month
last_contact_month
Cat_6_m***y    11737
Cat_3_j***l     6120
Cat_1_a***g     5191
Cat_4_j***n     4539
Cat_7_n***v     3482
Cat_0_a***r     2230
Cat_8_o***t      602
Cat_9_s***p      478
Cat_5_m***r      457
Cat_2_d***c      153
Name: count, dtype: int64

last_contact_weekday
last_contact_weekday
Cat_2_t***u    7353
Cat_1_m***n    7243
Cat_4_w***d    6898
Cat_3_t***e    6883
Cat_0_f***i    6612
Name: count, dtype: int64

previous_campaign_outcome
previous_campaign_outcome
Cat_1_n***t    30181
Cat_0_f***e     3646
Cat_2_s***s     1162
Name: count, dtype: int64

prev_campaign_status
prev_campaign_status
no_prev_campaign             30181
prev_campaign_gap_unknown     3519
prev_campaign_gap_known       1289
Name: count, dtype: int64

In [29]:
home_unk = df["has_home_loan"] == "Cat_1_u***n"
pers_unk = df["has_personal_loan"] == "Cat_1_u***n"
emp_839  = df["employment_type"] == "Cat_10_u***d"

print("home unknown vs personal unknown:")
display(pd.crosstab(home_unk, pers_unk))

print("\nhome unknown vs employment Cat_10_u***d:")
display(pd.crosstab(home_unk, emp_839))

home unknown vs personal unknown:

has_personal_loan  False  True
has_home_loan
False              34150      0
True                   0    839

home unknown vs employment Cat_10_u***d:

employment_type  False  True
has_home_loan
False            33331    819
True               819     20